In [1]:
import cv2
import numpy as np
import nbimporter
import util
from least_squares_M_solver import *
from svd_M_solver import *

Importing Jupyter notebook from util.ipynb
Importing Jupyter notebook from least_squares_M_solver.ipynb
Importing Jupyter notebook from svd_M_solver.ipynb


In [2]:
# Estimate camera projection matrix
def ps3_1a():
    pts_2d = util.load_file('pts2d-norm-pic_a.txt')
    pts_3d = util.load_file('pts3d-norm.txt')
    
    # test results using a least squares solver
    M, res = least_squares_M_solver(pts_2d, pts_3d)
    pt_2d_proj = np.dot(M, np.append(pts_3d[-1],1))
    pt_2d_proj = pt_2d_proj[:2] / pt_2d_proj[2]
    res = np.linalg.norm(pts_2d[-1] - pt_2d_proj)
    print('Results with least squares:')
    print('M=\n%s'%M)
    print('Point %s projected to point %s'%(pts_2d[-1] ,pt_2d_proj))
    print('Residual: %.4f\n'%res)
    
    # test results using SVD solver
    M = svd_M_solver(pts_2d, pts_3d)
    pt_2d_proj = np.dot(M, np.append(pts_3d[-1],1))
    pt_2d_proj = pt_2d_proj[:2] / pt_2d_proj[2]
    res = np.linalg.norm(pts_2d[-1] - pt_2d_proj)
    print('Results with SVD:')
    print('M=\n%s'%M)
    print('Point %s projected to point %s'%(pts_2d[-1] ,pt_2d_proj))
    print('Residual: %.4f\n'%res)
    
ps3_1a()

Results with least squares:
M=
[[ 0.76785833 -0.49384797 -0.02339789  0.00674443]
 [-0.08521339 -0.09146819 -0.90652329 -0.08775678]
 [ 0.18265015  0.2988292  -0.07419244  1.        ]]
Point [ 0.1406     -0.45269999] projected to point [ 0.14190583 -0.45183984]
Residual: 0.0016

Results with SVD:
M=
[[ 0.45827553 -0.29474238 -0.0139575   0.00402579]
 [-0.05085589 -0.05458471 -0.54105991 -0.05237592]
 [ 0.10900958  0.1783455  -0.04426783  0.59682047]]
Point [ 0.1406     -0.45269999] projected to point [ 0.14190602 -0.451843  ]
Residual: 0.0016

