In [2]:
import numpy as np

In [14]:
num_pts = 4
A = np.random.randint(1, high=20, size=(2*num_pts,11))
b = np.zeros(2*num_pts, dtype=np.float32)
print(A, b)
print()
print(A[::2,:])
print()
print(A[1::2,:])

[[19 19 17  4  3 12  2 16 15 13 10]
 [12 14  6  9 15  6  2 18  8  2 11]
 [14 11  4 18 19 14 16  2  6 12 14]
 [ 7 15  8  8 15 19 10  8 18 12  1]
 [15  9 17 12 10 13 12 15  3  1  3]
 [17 13  6 18  8  2 18 12  1 18  9]
 [14 16 12 16  6 14 12 15 11 15 16]
 [ 1  3  1  6  2 11 12  5  5  5 11]] [ 0.  0.  0.  0.  0.  0.  0.  0.]

[[19 19 17  4  3 12  2 16 15 13 10]
 [14 11  4 18 19 14 16  2  6 12 14]
 [15  9 17 12 10 13 12 15  3  1  3]
 [14 16 12 16  6 14 12 15 11 15 16]]

[[12 14  6  9 15  6  2 18  8  2 11]
 [ 7 15  8  8 15 19 10  8 18 12  1]
 [17 13  6 18  8  2 18 12  1 18  9]
 [ 1  3  1  6  2 11 12  5  5  5 11]]


In [18]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
print(np.vstack([x, np.ones(len(x))]).T)
print(np.ones(len(x)))
print(np.vstack([x, np.ones(len(x))]))

[[ 0.  1.]
 [ 1.  1.]
 [ 2.  1.]
 [ 3.  1.]]
[ 1.  1.  1.  1.]
[[ 0.  1.  2.  3.]
 [ 1.  1.  1.  1.]]


In [58]:
pts_2d = np.array([[0, 1], [2, 3]])
x = pts_2d[:,0]
y = pts_2d[:,1]
print(np.append(pts_2d[-1], 1))
print()
a = np.array([1,2])
b = np.array([3,4])
print(2 * pts_2d.T)
num_pts = pts_2d.shape[0]
b = np.zeros(2*num_pts, dtype=np.float32)
b[::2] = x
b[1::2] = y
print(b)
print(pts_2d.flatten().astype('float32'))

[2 3 1]

[[0 4]
 [2 6]]
[ 0.  1.  2.  3.]
[ 0.  1.  2.  3.]


In [36]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
np.linalg.lstsq(A, y)

(array([ 1.  , -0.95]), array([ 0.05]), 2, array([ 4.10003045,  1.09075677]))

In [69]:
import random
num_pts = 10
num_calibration_pts = 5
num_test_pts = 4
idxs = random.sample(range(num_pts), num_calibration_pts)
print(idxs)
test_idxs = set(range(num_pts)) - set(idxs)
print(test_idxs)
test_idxs = random.sample(test_idxs, num_test_pts)
print(test_idxs)

[2, 9, 7, 5, 3]
{0, 1, 4, 6, 8}
[0, 8, 4, 1]


In [73]:
a = b = [0, 0]
a[0] = 1
print(b)

[1, 0]


In [85]:
a = np.array([[1,2], [1,2], [1,2]])
b = np.array([[4,6], [4,6], [4,6]])
print(a-b)
np.linalg.norm(a - b)

[[-3 -4]
 [-3 -4]
 [-3 -4]]


8.6602540378443873