In [1]:
imgs = ['transA.jpg', 'transB.jpg', 'simA.jpg', 'simB.jpg']
imgs[0:3:2]

['transA.jpg', 'simA.jpg']

In [10]:
import numpy as np
import cv2
window_size = 5
c = np.zeros((window_size, window_size), dtype=np.float32);
window_size_half = window_size // 2
print(c)
c[window_size_half, window_size_half] = 1.0
print(c)

w = cv2.GaussianBlur(c, (window_size,)*2, 0)
print(w)
a, b = w.shape
print(a, b)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.015625  0.03125   0.046875  0.03125   0.015625]
 [ 0.03125   0.0625    0.09375   0.0625    0.03125 ]
 [ 0.046875  0.09375   0.140625  0.09375   0.046875]
 [ 0.03125   0.0625    0.09375   0.0625    0.03125 ]
 [ 0.015625  0.03125   0.046875  0.03125   0.015625]]
5 5


In [40]:
a = np.array([[1,2], [2,1]])
b = np.array([[3,4], [4,3]])
c = np.array([a,b])
d = np.array([[2,2], [2,2]])
print(d*c)
# np.asarray(map(np.sum, d*c))
np.asarray([np.sum(l) for l in d*c])

a * (a > 1)
1e-2

[[[2 4]
  [4 2]]

 [[6 8]
  [8 6]]]


0.01